### ISSUE TITLE
Why not try to normalise to actual Pointer Events?

### ISSUE THREAD

**Issue by patrickhlauke** [mozilla/pointer.js#3]
As cool as it is to see efforts moving in this direction, I have to wonder what the advantage of normalising to pseudo-pointer events, which are incompatible with actual W3C Pointer Events CR, is?

**Comment by potch** [comment]
This is an excellent idea! I'll take a look at the spec.

**Comment by patrickhlauke** [comment]
See also the discussion here https://bugzilla.mozilla.org/show_bug.cgi?id=822898#c24

**Comment by gstroup** [comment]
Agree, that this project should follow the W3C recommendation: http://www.w3.org/TR/pointerevents/
I was excited to find this project, since I thought it was following the spec, but I guess it's not.  If you're interested, I may be able to help with coding to support the spec.

**Comment by potch** [comment]
I'm highly interested, but highly busy. I'm going to work at updating this code to the spec soon, but would also appreciate any help!

**Comment by hexalys** [comment]
FYI, There is already a polyfill for the pointer Events specs: http://handjs.codeplex.com, or https://github.com/toolkitchen/PointerEvents, and a jquery version at: https://github.com/jquery/jquery-pointer-events
